micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost/cdc?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
